# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup pytools
      env:
        jmail: ${{ secrets.jmail }}
      run: |
        curl -O https://raw.githubusercontent.com/w311ang/pytools/main/pytools.py
        curl -O https://raw.githubusercontent.com/w311ang/pytools/main/aes.py
    - name: Run
      env:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        talk_pw: ${{ secrets.talk_pw }}
        pw: ${{ secrets.pw }}
        host: ${{ secrets.host }}
      run: |
        python signin.py
